### ISSUE TITLE
"You win!" and "PlayAgain!" sticking on screen.

### ISSUE THREAD

**Issue by Satharus** [ahmedabuamra/MinesweeperGame#18]
![image](https://user-images.githubusercontent.com/29730368/39658525-cd1414ec-5015-11e8-9491-45bc4058cc0a.png)
After finishing a custom game, "You win!" and "PlayAgain!" stay on the screen and don't go away. They also prevent you from playing other games, even though they load correctly.

**Comment by Satharus** [comment]
This error persisted after winning any game, not just custom games. 
Also, the "playagain!" button isn't working, the only way to exit is to return to the main menu.

**Comment by u3forge** [comment]
Solved
