### ISSUE TITLE
Runtime error and crash on clicking.

### ISSUE THREAD

**Issue by Satharus** [ahmedabuamra/MinesweeperGame#19]
![image](https://user-images.githubusercontent.com/29730368/39658553-4fe327c8-5016-11e8-82ef-bd065870f215.png)

Clicking on the tile (A,D) Crashed the GUI,  giving me a runtime error.

**Comment by u3forge** [comment]
maybe because of '%' didn't put it in the condition 
But it is put now and didn't get any runtime Errors .
